<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Traffic Volume Summary — {{ $site['road_name'] ?? 'Site '.$site['id'] }}</title>
    <style>
        @page { margin: 24mm 18mm; }
        body { font-family: DejaVu Sans, sans-serif; color: #111; font-size: 11pt; }
        h1 { font-size: 16pt; margin: 0 0 4pt; }
        .subtitle { color: #666; font-size: 9pt; margin-bottom: 16pt; }
        table.facts { width: 100%; border-collapse: collapse; }
        table.facts td { padding: 4pt 6pt; border-bottom: 1pt solid #eee; vertical-align: top; }
        table.facts td.label { width: 40%; color: #555; font-weight: bold; }
        .level-badge {
            display: inline-block; padding: 2pt 8pt; border-radius: 4pt; color: #fff;
            font-weight: bold; font-size: 11pt;
        }
        .level-LV { background: #4caf50; }
        .level-1  { background: #2196f3; }
        .level-2  { background: #ff9800; }
        .level-3  { background: #f44336; }
        .map { margin-top: 12pt; }
        .map img { width: 100%; border: 1pt solid #ddd; }
        .footer { margin-top: 18pt; color: #777; font-size: 8pt; }
    </style>
</head>
<body>
    <h1>Traffic Volume Summary</h1>
    <div class="subtitle">For inclusion in TMP under NZGTTM &middot; Generated by RoadBase &middot; {{ $generatedAt }}</div>

    <table class="facts">
        <tr><td class="label">Road</td><td>{{ $site['road_name'] ?? 'Unknown' }}</td></tr>
        <tr><td class="label">Region</td><td>{{ $site['region'] ?? '—' }}</td></tr>
        <tr><td class="label">Location (lat, lng)</td>
            <td>{{ number_format($site['lat'], 6) }}, {{ number_format($site['lng'], 6) }}</td></tr>
        <tr><td class="label">AADT</td>
            <td>{{ $site['aadt'] !== null ? number_format($site['aadt']).' vpd' : 'N/A' }}</td></tr>
        <tr><td class="label">NZGTTM Road Level</td>
            <td>
                @if ($site['nzgttm_level'])
                    <span class="level-badge level-{{ $site['nzgttm_level'] }}">{{ $site['nzgttm_level'] }}</span>
                    <div style="font-size: 9pt; color: #555; margin-top: 4pt;">{{ $levelDescription }}</div>
                @else
                    N/A
                @endif
            </td>
        </tr>
        <tr><td class="label">Speed limit</td>
            <td>{{ $site['speed_limit_kmh'] !== null ? $site['speed_limit_kmh'].' km/h' : 'N/A' }}</td></tr>
        <tr><td class="label">Heavy vehicles</td>
            <td>{{ $site['heavy_vehicle_pct'] !== null ? $site['heavy_vehicle_pct'].' %' : 'N/A' }}</td></tr>
        <tr><td class="label">Peak hour volume</td>
            <td>{{ $site['peak_hour_volume'] !== null ? number_format($site['peak_hour_volume']).' vph' : 'N/A' }}</td></tr>
        <tr><td class="label">Peak hour start</td>
            <td>{{ $site['peak_hour_start'] ?? 'N/A' }}</td></tr>
        <tr><td class="label">Count date</td><td>{{ $site['count_date'] ?? 'N/A' }}</td></tr>
        <tr><td class="label">Source</td>
            <td>{{ $site['source_name'] }}@if ($site['source_url']) <br><span style="font-size: 9pt; color: #555;">{{ $site['source_url'] }}</span>@endif</td></tr>
        <tr><td class="label">RoadBase last synced</td><td>{{ $site['synced_at'] }}</td></tr>
    </table>

    @if ($staticMapUrl)
        <div class="map"><img src="{{ $staticMapUrl }}" alt="Site location"></div>
    @endif

    <div class="footer">
        RoadBase aggregates open-data traffic counts from NZTA, NSLR and councils. Always verify
        figures against the originating dataset before relying on them in a final TMP submission.
    </div>
</body>
</html>
