<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NZGTTM context — {{ $site['road_name'] ?? 'Site '.$site['id'] }}</title>
    <style>
        @page { margin: 22mm 18mm; }
        body { font-family: DejaVu Sans, sans-serif; color: #111; font-size: 10.5pt; }
        h1 { font-size: 16pt; margin: 0 0 4pt; }
        h2 { font-size: 11pt; margin: 14pt 0 6pt; color: #1f2937; border-bottom: 1pt solid #d1d5db; padding-bottom: 2pt; }
        .subtitle { color: #6b7280; font-size: 9pt; margin-bottom: 10pt; }
        .banner { background: #fef3c7; border: 1pt solid #f59e0b; color: #78350f;
                  padding: 6pt 9pt; font-size: 9.5pt; margin-bottom: 12pt; border-radius: 3pt; }
        table.facts { width: 100%; border-collapse: collapse; }
        table.facts td { padding: 3pt 6pt; border-bottom: 1pt solid #eee; vertical-align: top; }
        table.facts td.label { width: 38%; color: #555; font-weight: bold; }
        ul.zones { margin: 0; padding-left: 16pt; }
        .crashes { display: inline-block; margin-right: 12pt; }
        .crash-bad { color: #b91c1c; font-weight: bold; }
        .map { margin-top: 10pt; }
        .map img { width: 100%; border: 1pt solid #ddd; }
        .footer { margin-top: 16pt; color: #6b7280; font-size: 8pt; line-height: 1.5; }
        .mr { background: #eff6ff; border: 1pt solid #bfdbfe; padding: 6pt 9pt;
              font-size: 9pt; border-radius: 3pt; margin-top: 8pt; }
        a { color: #1d4ed8; text-decoration: none; }
    </style>
</head>
<body>
    <h1>NZGTTM Activity &amp; Environment Context</h1>
    <div class="subtitle">{{ $site['road_name'] ?? 'Unknown road' }} &middot; Generated by RoadBase &middot; {{ $generatedAt }}</div>

    <div class="banner">
        <strong>Context input — not a TMP.</strong>
        Use these figures as one input to your own NZGTTM 2023 risk assessment. The 2023 guide
        retired road levels and pre-approved schemes as substitutes for site-specific
        risk-based design.
    </div>

    <h2>Site</h2>
    <table class="facts">
        <tr><td class="label">Road</td><td>{{ $site['road_name'] ?? 'Unknown' }}</td></tr>
        <tr><td class="label">Region</td><td>{{ $site['region'] ?? '—' }}</td></tr>
        <tr><td class="label">Location (lat, lng)</td>
            <td>{{ number_format($site['lat'], 6) }}, {{ number_format($site['lng'], 6) }}</td></tr>
        <tr><td class="label">Road controlling authority</td>
            <td>{{ $site['rca'] ?? 'Unknown — verify with NSLR / council' }}</td></tr>
    </table>

    <h2>Network users</h2>
    <table class="facts">
        <tr><td class="label">AADT</td>
            <td>{{ $site['aadt'] !== null ? number_format($site['aadt']).' vpd' : 'N/A' }}</td></tr>
        <tr><td class="label">Heavy vehicles</td>
            <td>{{ $site['heavy_vehicle_pct'] !== null ? $site['heavy_vehicle_pct'].' %' : 'N/A' }}</td></tr>
        <tr><td class="label">Peak hour volume</td>
            <td>{{ $site['peak_hour_volume'] !== null ? number_format($site['peak_hour_volume']).' vph' : 'N/A' }}</td></tr>
        <tr><td class="label">Peak hour start</td>
            <td>{{ $site['peak_hour_start'] ?? 'N/A' }}</td></tr>
        <tr><td class="label">Count date</td><td>{{ $site['count_date'] ?? 'N/A' }}</td></tr>
    </table>

    <h2>Speed environment</h2>
    <table class="facts">
        <tr><td class="label">Posted speed limit</td>
            <td>{{ $site['speed_limit_kmh'] !== null ? $site['speed_limit_kmh'].' km/h' : 'N/A' }}</td></tr>
        <tr><td class="label">NSLR zones at this point</td><td>
            @if (empty($site['speed_zones']))
                No overlapping NSLR zone records.
            @else
                <ul class="zones">
                    @foreach ($site['speed_zones'] as $z)
                        <li>
                            {{ $z['speed_kmh'] ?? '?' }} km/h
                            @if ($z['type']) ({{ $z['type'] }}) @endif
                            @if ($z['zone_name']) — {{ $z['zone_name'] }} @endif
                        </li>
                    @endforeach
                </ul>
            @endif
        </td></tr>
    </table>

    <h2>Safety history (last {{ date('Y') - $site['crashes']['since_year'] }} yr, ~1 km radius)</h2>
    <table class="facts">
        <tr><td class="label">Total crashes since {{ $site['crashes']['since_year'] }}</td>
            <td><strong>{{ $site['crashes']['count'] }}</strong></td></tr>
        <tr><td class="label">By severity</td><td>
            <span class="crashes @if($site['crashes']['fatal']>0) crash-bad @endif">
                Fatal: {{ $site['crashes']['fatal'] }}
            </span>
            <span class="crashes @if($site['crashes']['serious']>0) crash-bad @endif">
                Serious: {{ $site['crashes']['serious'] }}
            </span>
            <span class="crashes">Minor: {{ $site['crashes']['minor'] }}</span>
            <span class="crashes">Non-injury: {{ $site['crashes']['non_injury'] }}</span>
        </td></tr>
    </table>

    <h2>Reference tools</h2>
    <div class="mr">
        <strong>Need an RP?</strong>
        Open <a href="{{ $mobileRoadUrl }}">Mobile Road</a> and use the coordinates above.
        Mobile Road handles GPS↔RP linear referencing for state highway, council and KiwiRail
        centrelines.
    </div>

    @if ($staticMapUrl)
        <h2>Location</h2>
        <div class="map"><img src="{{ $staticMapUrl }}" alt="Site location"></div>
    @endif

    <h2>Source</h2>
    <table class="facts">
        <tr><td class="label">Data source</td>
            <td>{{ $site['source_name'] }}@if ($site['source_url']) <br><span style="font-size: 9pt; color: #555;">{{ $site['source_url'] }}</span>@endif</td></tr>
        <tr><td class="label">RoadBase last synced</td><td>{{ $site['synced_at'] }}</td></tr>
    </table>

    <div class="footer">
        Reference: <a href="{{ $guide['url'] }}">{{ $guide['label'] }}</a>, Creative Commons
        Attribution 4.0. Always verify figures against the originating dataset before relying
        on them in a final TMP. Pre-approved schemes / generic plans must never be assumed
        applicable to a site without a fresh risk assessment (NZGTTM 2023, p.36).
    </div>
</body>
</html>
